[package]
name        = "rustsec-admin"
description = "Admin utility for maintaining the RustSec Advisory Database"
version     = "0.5.3"
authors     = ["Tony Arcieri <bascule@gmail.com>"]
license     = "Apache-2.0 OR MIT"
homepage    = "https://rustsec.org"
repository  = "https://github.com/RustSec/rustsec/tree/main/admin"
readme      = "README.md"
edition     = "2018"

[dependencies]
abscissa_core = "0.5"
crates-index = "0.18"
gumdrop = "0.7"
rustsec = { version = "0.24.3", path = "../rustsec", features = ["osv-export"] }
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"
termcolor = "1"
thiserror = "1"
toml = "0.5"
chrono = { version = "0.4", features = ["serde"] }
askama = "0.10"
rust-embed="6.2.0"
comrak = "0.12"
atom_syndication = "0.10"
xml-rs = "0.8"

[dev-dependencies]
abscissa_core = { version = "0.5", features = ["testing"] }
once_cell = "1.5"
